spring.application.name=LabLinkBackend

# db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/testingdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# migrations
spring.flyway.enabled=false

lablink.app.secret=agsucydhcnsdcjhsdkajmskaosjdasjicjasiocjaijcsjaiodjiasjdkjasdjioasjdoajsdiaosdajdianc
lablink.app.expiration=60000